wallpaper {
    monitor = DP-1
    path = /home/kurc/Pictures/wallpapers/wallpaper
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/kurc/Pictures/wallpapers/wallpaper
    fit_mode = cover
}
